# Site settings
title: Sam Deacon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    This website was built following Travis - "awesome", "devtips" - Neilson
    from his YouTube channel / playlist: 'DESIGN AND CODE my personal website'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: deaconsam10
github_username:  BeardyMrDeaks
exclude: [node_modules, gulpfile.js]

# Build settings
markdown: redcarpet

sass:
    sass_dir: assets/css
